name: Deploy Service

on:
  push:
    branches:
      - main
    paths:
      - 'apps/server/**'
      - 'packages/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. my-service-account@my-project.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        env:
          IMAGE_NAME: ${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPOSITORY_SERVICE }}/service:${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME -f ./apps/server/Dockerfile ./apps/server
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.GCP_CLOUD_RUN_NAME_SERVICE }} \
            --image=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPOSITORY_SERVICE }}/service:${{ github.sha }} \
            --region ${{ vars.GCP_CLOUD_RUN_REGION }} \
            --platform managed \
            --quiet
